### ISSUE TITLE
progress_bar used without setting NO_OUTPUT_BUFFERING.

### ISSUE THREAD

**Issue by ewallah** [open-lms-open-source/moodle-tool_themetester#1]
Due to MDL-57809 the progress_bar suffered some changes. As a result behat is throwing debug messages:

Scenario: No warnings thrown from renderers # admin/tool/themetester/tests/behat/themetester.feature:30
      And I follow "Progress Bars"              # admin/tool/themetester/tests/behat/themetester.feature:78
        debugging() message/s found:
        progress_bar used without setting NO_OUTPUT_BUFFERING.
        line 4751 of /lib/outputcomponents.php: call to debugging()
        line 51 of /admin/tool/themetester/progress.php: call to progress_bar->__construct()

Adding the line define('NO_OUTPUT_BUFFERING', true); on top of the file progress.php is a fix.

Moodle 3.3+ (Build: 20170629)

**Comment by davidscotson** [comment]
Hi, thanks for the report, this is now fixed internally, so our process should push the fix out to the master branch over the next few days.

**Comment by ewallah** [comment]
THX
